### PR TITLE
And one more nnbd migration :)

### PR DESCRIPTION
**Pull request by bsutton**

### CODE REVIEW

**Comment by bsutton** [comment]
@mezoni just checking that you saw my pull request.

**Comment by mezoni** [comment]
Hello, Brett!
Thank you again.
Accepted (with some changes) and published.

**Comment by bsutton** [comment]
Again thank you for the prompt response.

**Comment by nt4f04uNd** [comment]
@mezoni i don't have any other way to ask you about this so i will ask here - why are issues closed in this repository?

**Comment by mezoni** [comment]
@nt4f04uNd
Thanks for the question.
Fixed.

**Pull request merged**
